namespace: atomist
name: github-branch-protection-rules-skill
displayName: GitHub Branch Protection Rules Skill
description: Share branch protection rules across Repos
license: unknown
author: atomist
triggers:
  - OnAnyPush
  - OnPullRequest
resourceProviders:
  - name: github
    description: GitHub
    typeName: GitHubAppResourceProvider
    minRequired: 1
    maxAllowed: 1
  - name: chat
    displayName: Chat
    typeName: ChatProvider
    description: Chat
    minRequired: 0
    maxAllowed: 1
commands:
  - name: sync
    description: check all the Repo configs
    pattern: ^sync branch protection rules.*$
iconUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
homepageUrl: "https://github.com/atomist-skills/github-branch-protection-rules-skill"
parameters:
  - string:
      description: list the Repo topic you use to set this policy
      displayName: Choose Topic
      name: topic
      placeHolder: topicname
      required: true
  - string:
      description: Enable branch protection rules for the branches matching this name or pattern.
      displayName: Branch name pattern
      name: branchPattern
      placeHolder: "main,default"
      required: true
  - int:
      name: required_approving_review_count
      displayName: Require pull request reviews before merging
      description: Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6.
      maximum: 6
      minimum: 1
      required: false
  - boolean:
      name: dismiss_stale_reviews
      displayName: "Require pull request reviews: Dismiss Stale Reviews"
      description: Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.
      required: false
  - boolean:
      name: require_code_owner_reviews
      displayName: "Require pull request reviews: Require Code Owner Reviews"
      description: Blocks merging pull requests until [code owners](https://help.github.com/articles/about-code-owners/) review them.
      required: false
  - stringArray:
      name: required_status_checks
      displayName: Required Status Checks
      description: Specify which status checks must pass before branches can be merged.  See [github documentation](https://docs.github.com/en/github/administering-a-repository/about-required-status-checks).
      required: false
  - boolean:
      name: required_signed_commits
      displayName: Require signed commits
      description: Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch.  Your repository must allow squash merging or rebase merging before you can enable a linear commit history.
      default: false
      required: false
  - boolean:
      name: required_linear_history
      displayName: Required Linear History
      description: Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch.  Your repository must allow squash merging or rebase merging before you can enable a linear commit history.
      default: false
      required: false
  - boolean:
      description: Enforce branch protection rules for repostitory administrators. Set to true to enforce required status checks for repository administrators.
      displayName: Include administrators
      name: enforce_admins
      required: false
  - boolean:
      name: allow_force_pushes
      displayName: Allow force pushes
      description: Permit force pushes for all users with push access.
      default: false
      required: false
  - boolean:
      name: allow_deletions
      displayName: Allow deletions
      description: Allow users with push access to delete matching branches.
      default: false
      required: false
  - schedule:
      description: Keep repository branch protection configurations current. If set, repository branch protection configurations will be checked and updated to this configuration on the set schedule.
      displayName: Schedule
      name: schedule
      defaultValue: 0 */6 * * *
      placeHolder: 0 */6 * * *
      required: false
  - repoFilter:
      description: Select repositories that should have the standard set of Labels
      displayName: Repo Filter
      name: RepoFilter
      required: false
artifacts:
  gcf:
    - entryPoint: eventhandler
      runtime: nodejs10
      name: do-it-on-node
      memory: 512
      timeout: 60
